name: flutter_architecture_template
description: Flutter Architecture Template

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: ^5.0.4
  dio: ^4.0.6
  animate_do: ^3.0.2
  json_serializable: ^6.6.0
  json_annotation: ^4.8.0
  lottie: ^2.2.0
  flutter_mobx: ^2.0.6+5
  connectivity_plus: ^3.0.2
  hive_flutter: ^1.1.0
  permission_handler: ^10.2.0
  fluttertoast: ^8.1.2
  keyboard_dismisser: ^3.0.0
  google_nav_bar: ^5.0.6
  flutter_svg: ^1.1.6
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.5
  vexana: ^3.3.2
  shared_preferences: ^2.0.17
  bot_toast: ^4.0.3
  get_it: ^7.2.0
  persistent_bottom_nav_bar: ^5.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  mobx_codegen: ^2.1.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lottie/
    - assets/svg/
  

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
